export const CATEGORIES = [
  "All",
  "Creatine",
  "Protein",
  "Carbs",
  "Pre-Workout",
  "Vitamins",
  "Amino Acids",
];

export const defaultProducts = [
  {
    id: "1",
    name: "Creatine Monohydrate Pure",
    category: "Creatine",
    price: 5600,
    oldPrice: 7100,
    stock: 10,
    description: "مكمل كرياتين نقي لزيادة القوة والحجم العضلي والتحمل أثناء التمارين الشاقة.",
    image: "/images/product-01.jpg",
    available: true,
  },
  {
    id: "2",
    name: "Whey Protein Isolate",
    category: "Protein",
    price: 1500,
    oldPrice: 2050,
    stock: 10,
    description: "بروتين واي معزول سريع الامتصاص لبناء العضلات الصافية والاستشفاء السريع.",
    image: "/images/product-02.jpg",
    available: true,
  },
  {
    id: "3",
    name: "Complex Carbs Fuel",
    category: "Carbs",
    price: 850,
    oldPrice: 1075,
    stock: 10,
    description: "مصدر كربوهيدرات معقدة لإمداد الجسم بالطاقة الاستثنائية أثناء التمرين.",
    image: "/images/product-03.jpg",
    available: true,
  },
  {
    id: "4",
    name: "Extreme Pre-Workout Energy",
    category: "Pre-Workout",
    price: 3950,
    oldPrice: 4950,
    stock: 10,
    description: "تركيبة طاقة مركزة لزيادة الضخ العضلي والتركيز قبل التمرين.",
    image: "/images/product-04.jpg",
    available: true,
  },
  {
    id: "5",
    name: "Gold Whey Protein",
    category: "Protein",
    price: 1200,
    oldPrice: 1500,
    stock: 10,
    description: "واي بروتين عالي الجودة يدعم بناء وتغذية العضلات بشكل يومي.",
    image: "/images/product-05.jpg",
    available: true,
  },
  {
    id: "6",
    name: "Creatine Micronized",
    category: "Creatine",
    price: 4200,
    oldPrice: 4850,
    stock: 10,
    description: "كرياتين مايكرونايزد سريع الذوبان والامتصاص لنتائج أسرع.",
    image: "/images/product-06.jpg",
    available: true,
  },
  {
    id: "7",
    name: "Mass Gainer Carbs",
    category: "Carbs",
    price: 1000,
    oldPrice: 1350,
    stock: 10,
    description: "مكمل ضخامة عضلية وزيادة وزن يمدك بسعرات حرارية عالية.",
    image: "/images/product-07.jpg",
    available: true,
  },
  {
    id: "8",
    name: "Explosive Pump Booster",
    category: "Pre-Workout",
    price: 2400,
    oldPrice: 2850,
    stock: 10,
    description: "حافز قوي قبل التمرين لرفع معدل نشاط الدورة الدموية والتركيز.",
    image: "/images/product-08.jpg",
    available: true,
  },
  {
    id: "9",
    name: "Hydrolyzed Whey Protein",
    category: "Protein",
    price: 2100,
    oldPrice: 2850,
    stock: 10,
    description: "واي بروتين هيدروليزد أسرع امتصاصاً ومناسب جداً للهضم السلس.",
    image: "/images/product-09.jpg",
    available: true,
  },
  {
    id: "10",
    name: "Creatine Capsules",
    category: "Creatine",
    price: 800,
    oldPrice: 950,
    stock: 10,
    description: "كبسولات كرياتين سهلة الاستخدام والجرعات اليومية.",
    image: "/images/product-10.jpg",
    available: true,
  },
  {
    id: "11",
    name: "Casein Night Protein",
    category: "Protein",
    price: 1600,
    oldPrice: 2200,
    stock: 10,
    description: "بروتين الكازين بطيء الامتصاص لتغذية العضلات أثناء النوم.",
    image: "/images/product-11.jpg",
    available: true,
  },
  {
    id: "12",
    name: "Pure Oat Carbs",
    category: "Carbs",
    price: 2000,
    oldPrice: 2800,
    stock: 10,
    description: "كربوهيدرات صحية ناعمة وسهلة الخلط مع البروتين.",
    image: "/images/product-12.jpg",
    available: true,
  },
  {
    id: "13",
    name: "Pre-Workout No-Caffeine",
    category: "Pre-Workout",
    price: 1150,
    oldPrice: 1400,
    stock: 10,
    description: "مكمل قبل التمرين بدون كافيين مخصص للتمارين المسائية.",
    image: "/images/product-13.jpg",
    available: true,
  },
  {
    id: "14",
    name: "Plant-Based Protein",
    category: "Protein",
    price: 1150,
    oldPrice: 1400,
    stock: 10,
    description: "بروتين نباتي نقي 100% غني بالأحماض الأمينية الأساسية.",
    image: "/images/product-14.jpg",
    available: true,
  },
  {
    id: "15",
    name: "Creatine HCL Advanced",
    category: "Creatine",
    price: 1600,
    oldPrice: 2100,
    stock: 10,
    description: "كرياتين HCL المتقدم بامتصاص ممتاز وبدون احتباس ماء تحت الجلد.",
    image: "/images/product-15.jpg",
    available: true,
  },
];